### ISSUE TITLE
SQLITE migration

### ISSUE THREAD

**Issue by julianobarbosa** [pythonprobr/pythonpro-website#1182]
When start migration first time I get this error message:

```console
django.db.utils.NotSupportedError: Renaming the 'auth_user' table while in a transaction is not supported on SQLite < 3.26 because it would break referential integrity. Try adding `atomic = False` to the Migration class.
```

**Comment by renzon** [comment]
Well, to be honest I never use SQLite because a prefer having local environment similiar to production. So I install postgres locally all the time, in fact using docker. Check readme since I wrote the instructions there.

I run migrations agains an empty postgres db all the time, just check .travis file to confirm it ;)

**Comment by julianobarbosa** [comment]
OK !!!
